version: "3.3"

services:

  api:
    build:
      context: .
    image: deeplay
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
    networks:
      - internal

  worker:
    build:
      context: .
    image: deeplay
    env_file: docker-compose.env
    environment:
      SERVICES: worker
    depends_on:
      - nats
    networks:
      - internal

  nats:
    image: nats:2
    networks:
      - internal

networks:
  internal:

volumes:
  data:
