version: "3.3"

services:

  api:
    build:
      context: src/api
    image: deeplay-test-api
    env_file: docker-compose.env
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - nats
    restart: always
#    networks:
#      - internal

  worker:
    build:
      context: src/worker
    image: deeplay-test-worker
    env_file: docker-compose.env
    depends_on:
      - nats
    volumes:
      - ./data:/logs
    restart: always
############################################
#    replicas supported only for swarm mode
############################################
#    deploy:
#      mode: replicated
#      replicas: 4
#    networks:
#      - internal

  nats:
    image: nats
    restart: always
#    networks:
#      - internal

#networks:
#  internal:
#    driver: overlay

#volumes:
#  data: ./data
